name: torb

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system packages
        run: |
          sudo apt update

          sudo apt install -y \
            tor \
            golang-go \
            wget \
            unzip

      - name: Download webtunnel source
        run: |
          wget -O webtunnel.zip \
            https://github.com/tn3w/webtunnel/archive/refs/heads/main.zip

          unzip webtunnel.zip

      - name: Build webtunnel-client
        run: |
          cd webtunnel-main/client

          go build -o webtunnel-client

          sudo mv webtunnel-client /usr/bin/webtunnel-client

          sudo chmod +x /usr/bin/webtunnel-client

      - name: Install Python deps
        run: |
          pip install -r requirements.txt

      - name: Run parser
        run: |
          python main.py

      - name: Commit output
        run: |
          git config user.name "github-actions[bot]"

          git config user.email \
            "github-actions[bot]@users.noreply.github.com"

          git add output/

          git commit -m "update bridges" \
            || echo "nothing to commit"

          git push
